libcal.settings:
  type: config_object
  label: "LibCal API settings"
  mapping:
    libcal:
      type: mapping
      mapping:
        host:
          type: text
          label: "Host:"
        client_id:
          type: text
          label: "Client ID:"
        client_secret:
          type: text
          label: "Client Secret:"
        calendar_ids:
          type: text
          label: "Calendar IDs:"
        spaces_lids:
          type: text
          label: "Spaces location IDs:"
        hours_lids:
          type: text
          label: "Hours location IDs:"
        category_ids:
          type: text
          label: "Space category IDs:"
        policy_statements:
          type: text
          label: "Policy statements:"
