libcal.settings:
  type: config_object
  label: "LibCal API settings"
  mapping:
    libcal:
      type: mapping
      mapping:
        host:
          type: text
          label: "Host:"
        client_id:
          type: text
          label: "Client ID:"
        client_secret:
          type: text
          label: "Client Secret:"
        calendar_ids:
          type: text
          label: "Calendar IDs:"
